let data = [
    {"count":"1","className":"TestClass1","method":"testMethod1","testParams":"[username_u, password_u]","testDescription":"Test that user/admin is able to authenticate using valid credentials\u003cbr\u003eSteps:\u003cbr\u003e1. Open the Sign In page\u003cbr\u003e2. Insert valid username and password\u003cbr\u003e3. Click the Sign In button and verify that login is successful\u003cbr\u003e","time":"6622","status":"SUCCESS","exception":""},
    {"count":"2","className":"TestClass1","method":"testMethod2","testParams":"[username_a, password_a]","testDescription":"Test that user/admin is able to authenticate using valid credentials\u003cbr\u003eSteps:\u003cbr\u003e1. Open the Sign In page\u003cbr\u003e2. Insert valid username and password\u003cbr\u003e3. Click the Sign In button and verify that login is successful\u003cbr\u003e","time":"2725","status":"FAILED","exception": "Unable to login using valid credentials\u003cbr\u003e AssertionError: expected Home Page to be displayed after login\u003cbr\u003e File: LoginPage.java Line: 93\u003cbr\u003e Image: https://s3.amazonaws.com/ocn-media/1e16b10d-b38a-4efa-aca0-303cc24c2d12.png"},
    {"count":"3","className":"TestClass2","method":"testMethod3","testParams":"[creditCard1]","testDescription":"Test user can successfully buy product using eligible cards\u003cbr\u003eSteps:\u003cbr\u003e1. Having a selected product, open the Checkout page\u003cbr\u003e2. Click the Buy button and insert valid card dta\u003cbr\u003e3. Verify the purchase is successfull and the confirmation page is shown\u003cbr\u003e","time":"5353","status":"SKIPPED","exception":"Payment gateway wasn't loaded. Check the test environment setup and re-deploy"}, 
    {"count":"4","className":"TestClass2","method":"testMethod4","testParams":"[creditCard2]","testDescription":"Test user can successfully buy product using eligible cards\u003cbr\u003eSteps:\u003cbr\u003e1. Having a selected product, open the Checkout page\u003cbr\u003e2. Click the Buy button and insert valid card dta\u003cbr\u003e3. Verify the purchase is successfull and the confirmation page is shown\u003cbr\u003e","time":"4353","status":"SUCCESS","exception":""}, 
    {"count":"5","className":"TestClass3","method":"testMethod5","testParams":"[creditCard1]","testDescription":"Test user can successfully save valid cards for forther purchases\u003cbr\u003eSteps:\u003cbr\u003e1. While signed id, open the account page\u003cbr\u003e2. Click the add new cred card button\u003cbr\u003e3. Add valid card data and click the save button\u003cbr\u003e","time":"2353","status":"SUCCESS","exception":""},
    {"count":"6","className":"TestClass3","method":"testMethod6","testParams":"[creditCard2]","testDescription":"Test user can successfully save valid cards for forther purchases\u003cbr\u003eSteps:\u003cbr\u003e1. While signed id, open the account page\u003cbr\u003e2. Click the add new cred card button\u003cbr\u003e3. Add valid card data and click the save button\u003cbr\u003e","time":"9353","status":"FAILED","exception":"Error : Error communicating with the remote browser"},
    {"count":"7","className":"TestClass4","method":"testMethod7","testParams":"","testDescription":"Test that authenticated user can successfully log out from the application\u003cbr\u003eSteps:\u003cbr\u003e1. While signed id, click the Logout button\u003cbr\u003e2. Verify if the user is successfully logged out and login page is disaplyed\u003cbr\u003e","time":"3353","status":"SUCCESS","exception":""}]; 
let testRunName = 'Test Run Name'; 
let footerText='ProjectName';